import { NoteChapter } from '../types';

export const SAMPLE_NOTES: NoteChapter[] = [
  // 1. PHYSICS - GRADE 11 & 12
  {
    id: 'note-phys-11-u1',
    subjectId: 'physics',
    subjectName: 'Physics',
    grade: 'Grade 11',
    chapterNumber: 1,
    title: 'Kinematics & Two-Dimensional Vector Motion',
    readingTimeMinutes: 12,
    summary: 'Master resolution of vectors into components, kinematic equations in 2D, projectile trajectory mechanics, and relative velocity calculations.',
    tableOfContents: ['1. Vector Resolution & Addition', '2. Equations of Motion in 2D', '3. Projectile Motion Dynamics', '4. Key Formulas & Worked Example'],
    keyTerms: [
      { term: 'Vector Component', definition: 'The projection of a vector along a reference coordinate axis (e.g. Vx = V cos θ).' },
      { term: 'Trajectory', definition: 'The parabolic path followed by a projectile under the influence of gravity alone.' },
      { term: 'Time of Flight', definition: 'The total time a projectile remains airborne between launch and landing.' },
      { term: 'Range (R)', definition: 'The total horizontal distance traveled by a projectile on flat ground.' },
    ],
    formulas: [
      { name: 'Horizontal Velocity Component', formula: 'V_{0x} = V_0 \\cos\\theta', explanation: 'Initial horizontal velocity remains constant in ideal projectile motion.' },
      { name: 'Vertical Displacement', formula: 'y = V_{0y}t - \\frac{1}{2}gt^2', explanation: 'Calculates vertical height at time t where g = 9.8 m/s².' },
      { name: 'Maximum Height', formula: 'H_{max} = \\frac{V_0^2 \\sin^2\\theta}{2g}', explanation: 'Peak height attained when vertical velocity V_y becomes zero.' },
      { name: 'Horizontal Range', formula: 'R = \\frac{V_0^2 \\sin(2\\theta)}{g}', explanation: 'Maximum horizontal coverage for flat terrain launch.' },
    ],
    content: [
      {
        sectionTitle: '1. Vector Resolution & Addition',
        body: 'Physics problems in two dimensions require splitting vectors into orthogonal x (horizontal) and y (vertical) components. Because horizontal motion experiences zero acceleration (neglecting air resistance), Vx remains constant throughout flight.',
        bulletPoints: [
          'Choose a clean Cartesian coordinate system (+x to the right, +y upward).',
          'Break initial velocity V₀ into V₀x = V₀ cos θ and V₀y = V₀ sin θ.',
          'Analyze horizontal and vertical motions as two independent one-dimensional motions.',
        ],
        calloutBox: {
          title: 'Exam Pro-Tip',
          text: 'Air resistance is assumed to be negligible in standard Grade 11 physics unless explicitly stated. This means acceleration along the x-axis (a_x) is strictly 0 m/s².',
          type: 'tip',
        },
      },
      {
        sectionTitle: '2. Projectile Motion Dynamics',
        body: 'A projectile is any object fired or launched into space that moves under the sole influence of gravity. The path executed is a parabola defined by quadratic motion in the vertical axis combined with linear motion horizontally.',
        bulletPoints: [
          'At maximum height, the vertical velocity V_y becomes exactly 0 m/s.',
          'The time taken to reach maximum height equals the time to fall back down to launch level (t_up = t_down).',
          'The angle that maximizes range R on level ground is 45°.',
        ],
      },
    ],
  },
  {
    id: 'note-phys-12-u3',
    subjectId: 'physics',
    subjectName: 'Physics',
    grade: 'Grade 12',
    chapterNumber: 3,
    title: 'Electromagnetism & Faraday\'s Induction Law',
    readingTimeMinutes: 14,
    summary: 'Explore magnetic flux, Faraday\'s Law of Electromagnetic Induction, Lenz\'s Law of opposing induced currents, and AC generator transformers.',
    tableOfContents: ['1. Magnetic Flux (Φ)', '2. Faraday\'s Law of Induction', '3. Lenz\'s Rule & Direction of Current', '4. Transformer Efficiency'],
    keyTerms: [
      { term: 'Magnetic Flux (Φ)', definition: 'The measure of total magnetic field lines passing perpendicular through a given surface area (Weber, Wb).' },
      { term: 'Electromotive Force (EMF)', definition: 'The voltage generated by a battery or induced by magnetic flux changes in a circuit.' },
      { term: 'Lenz\'s Law', definition: 'The direction of an induced EMF/current always opposes the change in magnetic flux that created it.' },
    ],
    formulas: [
      { name: 'Magnetic Flux', formula: '\\Phi_B = B \\cdot A \\cos\\theta', explanation: 'Flux through area A in uniform magnetic field B.' },
      { name: 'Faraday\'s Law', formula: '\\mathcal{E} = -N \\frac{\\Delta\\Phi_B}{\\Delta t}', explanation: 'Induced electromotive force in an N-turn coil.' },
      { name: 'Transformer Ratio', formula: '\\frac{V_s}{V_p} = \\frac{N_s}{N_p} = \\frac{I_p}{I_s}', explanation: 'Voltage and current step-up or step-down relationship.' },
    ],
    content: [
      {
        sectionTitle: '1. Principles of Electromagnetic Induction',
        body: 'Whenever there is relative motion between a conductor and a magnetic field—or when the magnetic field through a stationary coil changes with time—an induced voltage (EMF) is established across the conductor terminals.',
        bulletPoints: [
          'Induction requires a changing flux (dΦ/dt ≠ 0). A steady, static magnetic field produces zero induced current.',
          'Increasing the number of wire loops N multiplies the resulting induced electromotive force.',
          'Rotating a planar coil at angular speed ω inside a uniform field creates alternating sinusoidal voltage ε(t) = NABω sin(ωt).',
        ],
        calloutBox: {
          title: 'Lenz\'s Law Sign Meaning',
          text: 'The negative sign in Faraday\'s formula ε = -N(dΦ/dt) is a direct reflection of the conservation of energy principle through Lenz\'s Law.',
          type: 'info',
        },
      },
    ],
  },

  // 2. MATHEMATICS - GRADE 10, 11 & 12
  {
    id: 'note-math-12-u2',
    subjectId: 'math',
    subjectName: 'Mathematics',
    grade: 'Grade 12',
    chapterNumber: 2,
    title: 'Differential Calculus & Derivatives',
    readingTimeMinutes: 15,
    summary: 'Comprehensive guide to limits, derivative definition, power rule, product rule, quotient rule, chain rule, and tangent line equations.',
    tableOfContents: ['1. Definition of the Derivative', '2. Essential Differentiation Rules', '3. The Chain Rule for Composite Functions', '4. Applications to Maxima & Minima'],
    keyTerms: [
      { term: 'Derivative', definition: 'The instantaneous rate of change of a function with respect to an independent variable f\'(x).' },
      { term: 'Critical Point', definition: 'A value x in the domain where f\'(x) = 0 or f\'(x) is undefined.' },
      { term: 'Tangent Line', definition: 'A straight line that touches a curve at a point with slope equal to the derivative at that point.' },
    ],
    formulas: [
      { name: 'Limit Definition of Derivative', formula: "f'(x) = \\lim_{h \\to 0} \\frac{f(x+h) - f(x)}{h}", explanation: 'First principles formula for calculating derivatives.' },
      { name: 'Power Rule', formula: "\\frac{d}{dx}[x^n] = n x^{n-1}", explanation: 'Brings down exponent n and reduces power by 1.' },
      { name: 'Product Rule', formula: "\\frac{d}{dx}[u \\cdot v] = u'v + uv'", explanation: 'Used when differentiating product of two functions.' },
      { name: 'Quotient Rule', formula: "\\frac{d}{dx}\\left[\\frac{u}{v}\\right] = \\frac{u'v - uv'}{v^2}", explanation: 'Derivative of u divided by v.' },
    ],
    content: [
      {
        sectionTitle: '1. Definition of the Derivative',
        body: 'Calculus allows us to calculate the exact slope of a curve at a single infinitesimal point. By taking the limit as secant distance h approaches zero, the secant line transforms into the tangent line.',
        bulletPoints: [
          'Differentiability requires continuity and smoothness (no sharp corners, cusps, or vertical tangents).',
          'Geometrically, f\'(a) represents the slope m of the tangent line at x = a.',
        ],
        calloutBox: {
          title: 'Important Rule',
          text: 'Always check if a function is continuous at a point before attempting to differentiate.',
          type: 'warning',
        },
      },
    ],
  },
  {
    id: 'note-math-10-u1',
    subjectId: 'math',
    subjectName: 'Mathematics',
    grade: 'Grade 10',
    chapterNumber: 1,
    title: 'Quadratic Equations & Polynomial Functions',
    readingTimeMinutes: 11,
    summary: 'Learn factoring, completing the square, discriminant analysis (b² - 4ac), nature of roots, quadratic graphs, and maximum/minimum vertex applications.',
    tableOfContents: ['1. Standard Quadratic Form', '2. The Quadratic Formula & Discriminant', '3. Vertex Form & Parabola Graphing'],
    keyTerms: [
      { term: 'Discriminant (Δ)', definition: 'The expression Δ = b² - 4ac used to determine whether roots are real, equal, or complex conjugate.' },
      { term: 'Vertex', definition: 'The highest or lowest turning point of a parabola located at x = -b/(2a).' },
    ],
    formulas: [
      { name: 'Quadratic Formula', formula: 'x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}', explanation: 'Calculates the roots of any quadratic equation ax² + bx + c = 0.' },
      { name: 'Discriminant', formula: '\\Delta = b^2 - 4ac', explanation: 'Δ > 0: 2 distinct real roots; Δ = 0: 1 real root; Δ < 0: 2 complex roots.' },
    ],
    content: [
      {
        sectionTitle: '1. Solving by Factoring & Formula',
        body: 'Quadratic equations represent degree-2 polynomials. Always rearrange terms to the standard form ax² + bx + c = 0 before computing discriminant or factoring.',
        bulletPoints: [
          'If the discriminant Δ > 0, the parabola intersects the x-axis at two distinct points.',
          'If Δ = 0, the parabola is tangent to the x-axis at its vertex.',
          'If Δ < 0, the parabola never crosses the x-axis.',
        ],
      },
    ],
  },
  {
    id: 'note-math-9-u1',
    subjectId: 'math',
    subjectName: 'Mathematics',
    grade: 'Grade 9',
    chapterNumber: 1,
    title: 'Number Systems, Exponents & Radicals',
    readingTimeMinutes: 10,
    summary: 'Master rational vs irrational numbers, real number properties, laws of exponents, simplifying surds/radicals, and rationalizing denominators.',
    tableOfContents: ['1. Real Number System', '2. Laws of Indices & Exponents', '3. Radicals and Surds', '4. Rationalizing Denominators'],
    keyTerms: [
      { term: 'Rational Number', definition: 'Any number expressible in the form p/q where p and q are integers and q ≠ 0.' },
      { term: 'Irrational Number', definition: 'A non-terminating, non-repeating decimal (such as √2, √3, or π).' },
      { term: 'Surd', definition: 'An expression containing an irrational root (such as √5 or ∛7).' },
    ],
    formulas: [
      { name: 'Product of Powers', formula: 'a^m \\cdot a^n = a^{m+n}', explanation: 'When multiplying like bases, add exponents.' },
      { name: 'Fractional Exponents', formula: 'a^{m/n} = \\sqrt[n]{a^m}', explanation: 'Index n becomes the root index while m is the power.' },
    ],
    content: [
      {
        sectionTitle: '1. Simplifying Exponents and Radicals',
        body: 'To simplify radical expressions, factor out perfect squares from under the square root symbol: √(a · b) = √a · √b.',
        bulletPoints: [
          'Never leave an irrational radical in the denominator of a fraction.',
          'Multiply numerator and denominator by the conjugate to rationalize binomial radical denominators.',
        ],
      },
    ],
  },

  // 3. CHEMISTRY - GRADE 10 & 12
  {
    id: 'note-chem-10-u3',
    subjectId: 'chemistry',
    subjectName: 'Chemistry',
    grade: 'Grade 10',
    chapterNumber: 3,
    title: 'Chemical Bonding & Molecular Geometry',
    readingTimeMinutes: 11,
    summary: 'Examine ionic crystal lattices, covalent electron sharing, Lewis electron-dot structures, electronegativity differences, and VSEPR molecular shapes.',
    tableOfContents: ['1. Ionic vs Covalent Bonding', '2. Electronegativity & Polarity', '3. Lewis Dot Structures & Octet Rule', '4. VSEPR Theory Shapes'],
    keyTerms: [
      { term: 'Ionic Bonding', definition: 'Electrostatic attraction between oppositely charged cations and anions formed by electron transfer.' },
      { term: 'Covalent Bonding', definition: 'Chemical bond formed when two nonmetal atoms share one or more pairs of valence electrons.' },
      { term: 'VSEPR Theory', definition: 'Valence Shell Electron Pair Repulsion model predicting 3D molecular geometry.' },
    ],
    formulas: [
      { name: 'Electronegativity Difference (ΔEN)', formula: '\\Delta EN = |EN_A - EN_B|', explanation: 'ΔEN > 1.7: Ionic; 0.4 to 1.7: Polar Covalent; < 0.4: Nonpolar Covalent.' },
    ],
    content: [
      {
        sectionTitle: '1. Predicting Bond Character',
        body: 'Atoms bond to achieve stable valence shell octets (8 electrons, resembling noble gas configurations). The difference in Pauling electronegativity determines if electrons are transferred or shared.',
        bulletPoints: [
          'Ionic compounds typically have high melting points and conduct electricity when molten or dissolved in water.',
          'Covalent compounds generally have lower melting points and exist as distinct neutral molecules.',
        ],
      },
    ],
  },
  {
    id: 'note-chem-12-u1',
    subjectId: 'chemistry',
    subjectName: 'Chemistry',
    grade: 'Grade 12',
    chapterNumber: 1,
    title: 'Chemical Equilibrium & Le Chatelier\'s Principle',
    readingTimeMinutes: 13,
    summary: 'Dynamic equilibrium principles, equilibrium constant Kc and Kp expressions, reaction quotient Q, and the effect of temperature, pressure, and concentration shifts.',
    tableOfContents: ['1. Dynamic Equilibrium Concept', '2. Equilibrium Expressions (Kc & Kp)', '3. Le Chatelier\'s Principle', '4. Haber-Bosch Process Application'],
    keyTerms: [
      { term: 'Dynamic Equilibrium', definition: 'A reversible chemical state where the rate of forward reaction equals the rate of reverse reaction.' },
      { term: 'Le Chatelier\'s Principle', definition: 'If an external stress is applied to a system at equilibrium, the system shifts to partially counteract that stress.' },
    ],
    formulas: [
      { name: 'Equilibrium Constant (Kc)', formula: 'K_c = \\frac{[C]^c [D]^d}{[A]^a [B]^b}', explanation: 'Ratio of equilibrium product concentrations to reactant concentrations.' },
    ],
    content: [
      {
        sectionTitle: '1. Le Chatelier\'s Shifts',
        body: 'When a chemical system is disturbed, it responds to minimize the applied stress:',
        bulletPoints: [
          'Increasing reactant concentration shifts equilibrium to the RIGHT (towards products).',
          'Increasing pressure shifts equilibrium towards the side with FEWER gas moles.',
          'Increasing temperature shifts an endothermic reaction (ΔH > 0) to the RIGHT, and an exothermic reaction (ΔH < 0) to the LEFT.',
        ],
      },
    ],
  },

  // 4. BIOLOGY - GRADE 11 & 12
  {
    id: 'note-bio-11-u2',
    subjectId: 'biology',
    subjectName: 'Biology',
    grade: 'Grade 11',
    chapterNumber: 2,
    title: 'Cellular Respiration, Glycolysis & Krebs Cycle',
    readingTimeMinutes: 13,
    summary: 'Step-by-step breakdown of aerobic glucose catabolism: Glycolysis in cytoplasm, Pyruvate Oxidation, Krebs Citric Acid Cycle, and the Electron Transport Chain (ETC).',
    tableOfContents: ['1. Overview of ATP Generation', '2. Glycolysis in Cytoplasm', '3. Citric Acid Cycle (Krebs)', '4. Oxidative Phosphorylation & Chemiosmosis'],
    keyTerms: [
      { term: 'ATP (Adenosine Triphosphate)', definition: 'The primary universal energy currency of cellular metabolic work.' },
      { term: 'Chemiosmosis', definition: 'The movement of protons across a membrane down their electrochemical gradient to drive ATP synthesis via ATP synthase.' },
      { term: 'Fermentation', definition: 'Anaerobic metabolic pathway regenerating NAD+ without oxygen.' },
    ],
    formulas: [
      { name: 'Aerobic Respiration Equation', formula: 'C_6H_{12}O_6 + 6O_2 \\rightarrow 6CO_2 + 6H_2O + 36\\text{ to }38\\text{ ATP}', explanation: 'Complete oxidation of one mole of glucose into carbon dioxide and water.' },
    ],
    content: [
      {
        sectionTitle: '1. The Four Metabolic Stages',
        body: 'Cellular respiration extracts biochemical energy stored in nutrient bonds through successive redox reactions.',
        bulletPoints: [
          'Glycolysis occurs in cytosol, requires no oxygen, and yields net 2 ATP + 2 NADH + 2 Pyruvates.',
          'Krebs Cycle runs in the mitochondrial matrix, releasing CO2 while reducing NAD+ and FAD into electron carriers.',
          'The Electron Transport Chain on the inner cristae generates approximately 32–34 ATP through oxidative phosphorylation.',
        ],
      },
    ],
  },

  // 5. ENGLISH - GRADE 10 & 12
  {
    id: 'note-eng-12-u1',
    subjectId: 'english',
    subjectName: 'English Language',
    grade: 'Grade 12',
    chapterNumber: 1,
    title: 'Advanced Grammar: Conditionals, Passive & Reported Speech',
    readingTimeMinutes: 10,
    summary: 'Comprehensive review of Zero, First, Second, and Third Conditionals, Passive Voice transformations across tenses, and indirect Reported Speech shifts.',
    tableOfContents: ['1. The 4 Conditional Structures', '2. Active to Passive Conversion Rules', '3. Reported Speech Tense Backshift', '4. Common Exam Traps'],
    keyTerms: [
      { term: 'Third Conditional', definition: 'Speculates about unreal past situations and outcomes: If + had + V3, would have + V3.' },
      { term: 'Passive Voice', definition: 'Grammatical voice where the subject undergoes the action rather than performing it.' },
    ],
    content: [
      {
        sectionTitle: '1. Master the Conditional Matrix',
        body: 'Conditionals test logic and verb tense consistency:',
        bulletPoints: [
          'Zero: If + present, present (Scientific facts & general truths).',
          'First: If + present, will + V1 (Realistic future possibilities).',
          'Second: If + past, would + V1 (Hypothetical or imaginary present/future).',
          'Third: If + past perfect, would have + V3 (Regrets and counterfactual past events).',
        ],
      },
    ],
  },

  // 6. INFORMATION TECHNOLOGY - GRADE 11 & 12
  {
    id: 'note-it-11-u1',
    subjectId: 'it',
    subjectName: 'Information Technology',
    grade: 'Grade 11',
    chapterNumber: 1,
    title: 'Computer Networks, OSI Model & Topologies',
    readingTimeMinutes: 11,
    summary: 'Examine LAN/WAN networks, OSI 7-layer reference architecture, TCP/IP protocol suite, IP addressing, Star/Mesh topologies, and cyber threat vectors.',
    tableOfContents: ['1. Network Topologies', '2. The 7 Layers of the OSI Model', '3. TCP/IP Protocols & Port Numbers', '4. Network Security & Firewalls'],
    keyTerms: [
      { term: 'OSI Model', definition: 'Open Systems Interconnection 7-layer framework standardizing computer communication.' },
      { term: 'IP Address', definition: 'A unique numerical label assigned to every device connected to a computer network.' },
      { term: 'Firewall', definition: 'A security system monitoring and filtering incoming and outgoing network traffic.' },
    ],
    content: [
      {
        sectionTitle: '1. OSI 7-Layer Reference Stack',
        body: 'Memorize the layers from bottom to top: Physical (1), Data Link (2), Network (3), Transport (4), Session (5), Presentation (6), Application (7). (Mnemonic: Please Do Not Throw Sausage Pizza Away).',
        bulletPoints: [
          'Layer 3 (Network): Handles logical IP addressing and router packet forwarding.',
          'Layer 4 (Transport): Provides reliable end-to-end transport (TCP) and speed-oriented transport (UDP).',
          'Layer 7 (Application): Provides protocols used directly by end-user software (HTTP, HTTPS, DNS, SMTP).',
        ],
      },
    ],
  },

  // 7. HISTORY - GRADE 11 & 12
  {
    id: 'note-hist-11-u2',
    subjectId: 'history',
    subjectName: 'History',
    grade: 'Grade 11',
    chapterNumber: 2,
    title: 'The Industrial Revolution & Global Transformations',
    readingTimeMinutes: 12,
    summary: 'Analyze the origins of industrialization in Great Britain, steam engine innovations, demographic shifts to urban centers, and economic ideologies of capitalism vs socialism.',
    tableOfContents: ['1. Agrarian Revolution & Inventions', '2. Urbanization & Social Classes', '3. Spread to Europe & Americas', '4. Rise of Trade Unions & Labor Laws'],
    keyTerms: [
      { term: 'Industrial Revolution', definition: 'The transformation from agrarian handicraft economies to machine-driven industrial manufacturing beginning in Britain circa 1760.' },
      { term: 'Urbanization', definition: 'The mass migration of rural populations into booming industrial cities.' },
      { term: 'Laissez-faire', definition: 'Economic policy advocating zero government intervention in free market operations.' },
    ],
    content: [
      {
        sectionTitle: '1. Why Britain Industrialized First',
        body: 'Britain possessed abundant coal and iron ore reserves, stable parliamentary governance, vast maritime colonial markets, capital for investment, and innovative inventors like James Watt and Richard Arkwright.',
        bulletPoints: [
          'The Enclosure Acts concentrated land ownership and supplied abundant cheap factory labor.',
          'Steam power revolutionized textile spinning and railroad logistics.',
          'Shift from domestic cottage industries to the factory system.',
        ],
      },
    ],
  },

  // 8. GEOGRAPHY - GRADE 12
  {
    id: 'note-geog-12-u1',
    subjectId: 'geography',
    subjectName: 'Geography',
    grade: 'Grade 12',
    chapterNumber: 1,
    title: 'Geomorphology, Plate Tectonics & Horn of Africa Rift System',
    readingTimeMinutes: 14,
    summary: 'Master lithospheric plate movements, convergent vs divergent boundaries, faulting and folding mechanisms, and the geological formation of the Main Ethiopian Rift Valley.',
    tableOfContents: ['1. Theory of Continental Drift & Tectonics', '2. Boundary Types & Volcanism', '3. The East African Rift System', '4. Mineral Resources & Soil Dynamics'],
    keyTerms: [
      { term: 'Plate Tectonics', definition: 'The geological model describing large-scale motions of Earth\'s lithosphere over the asthenosphere.' },
      { term: 'Rift Valley', definition: 'A linear lowland between several highlands or mountain ranges created by geological rifting and normal faulting.' },
      { term: 'Subduction Zone', definition: 'A convergent boundary where one tectonic plate sinks beneath another into the Earth\'s mantle.' },
    ],
    formulas: [
      { name: 'Rifting Extension Rate', formula: 'v = \\frac{d}{t}', explanation: 'Average rate of tectonic divergence, typically 2 to 5 mm/year in the Ethiopian Rift.' },
    ],
    content: [
      {
        sectionTitle: '1. Plate Boundaries & Rift Mechanics',
        body: 'Earth\'s outer crust is fractured into rigid tectonic plates that float upon the semi-fluid asthenosphere. Tectonic forces manifest at three primary boundary types: divergent (spreading), convergent (colliding), and transform (sliding).',
        bulletPoints: [
          'Divergent boundaries create mid-ocean ridges and continental rift valleys like the Afar Triple Junction.',
          'Convergent oceanic-continental boundaries generate volcanic mountain arcs and deep ocean trenches.',
          'Transform boundaries cause intense horizontal shear earthquakes.',
        ],
      },
    ],
  },

  // 9. CIVICS & ETHICS - GRADE 10
  {
    id: 'note-civ-10-u1',
    subjectId: 'civics',
    subjectName: 'Civics & Ethics',
    grade: 'Grade 10',
    chapterNumber: 1,
    title: 'Constitutionalism, Rule of Law & Human Rights',
    readingTimeMinutes: 11,
    summary: 'Explore constitutional principles, separation of powers, the Rule of Law, Universal Declaration of Human Rights, and democratic citizenship responsibilities.',
    tableOfContents: ['1. Elements of a Democratic Constitution', '2. The Rule of Law vs Autocracy', '3. Three Generations of Human Rights', '4. Civic Duties of Citizens'],
    keyTerms: [
      { term: 'Constitutionalism', definition: 'The political philosophy holding that governmental authority is derived from and limited by a fundamental body of constitutional law.' },
      { term: 'Rule of Law', definition: 'The legal principle that law applies equally to all citizens and leaders without arbitrary favoritism.' },
      { term: 'Popular Sovereignty', definition: 'The principle that state legitimacy and governing power emanate from the will and consent of the people.' },
    ],
    content: [
      {
        sectionTitle: '1. Pillars of Constitutional Democracy',
        body: 'A robust democratic constitution limits state power through checks and balances among the Legislative, Executive, and Judicial branches.',
        bulletPoints: [
          'Protects minority rights and civil liberties against majoritarian abuse.',
          'Mandates periodic, free, fair, and competitive multi-party elections.',
          'Upholds transparency, judicial independence, and freedom of expression.',
        ],
      },
    ],
  },

  // 10. ECONOMICS - GRADE 11
  {
    id: 'note-econ-11-u1',
    subjectId: 'economics',
    subjectName: 'Economics',
    grade: 'Grade 11',
    chapterNumber: 1,
    title: 'Scarcity, Opportunity Cost & Supply/Demand Equilibrium',
    readingTimeMinutes: 12,
    summary: 'Understand the fundamental economic problem of scarcity, production possibility frontiers (PPF), law of demand, law of supply, and market clearing equilibrium price.',
    tableOfContents: ['1. The Economic Problem: Scarcity & Choice', '2. Production Possibilities Frontier (PPF)', '3. Demand, Supply & Market Equilibrium', '4. Price Elasticity of Demand'],
    keyTerms: [
      { term: 'Scarcity', definition: 'The condition where unlimited human wants exceed limited productive resources.' },
      { term: 'Opportunity Cost', definition: 'The forgone benefit of the next best alternative given up in a decision.' },
      { term: 'Market Equilibrium', definition: 'The price and quantity point where Quantity Demanded (Qd) exactly equals Quantity Supplied (Qs).' },
    ],
    formulas: [
      { name: 'Price Elasticity of Demand (PED)', formula: 'PED = \\left| \\frac{\\% \\Delta Q_d}{\\% \\Delta P} \\right|', explanation: 'Measure of responsiveness of quantity demanded to price changes.' },
    ],
    content: [
      {
        sectionTitle: '1. Scarcity & The Production Possibility Frontier',
        body: 'Every society must address three fundamental questions: What to produce? How to produce? And For whom to produce? The PPF curve illustrates trade-offs and efficiency.',
        bulletPoints: [
          'Points on the PPF represent full, productive efficiency.',
          'Points inside the PPF represent unemployment or inefficient resource utilization.',
          'Points outside the PPF are unobtainable given current technology and resources.',
        ],
      },
    ],
  },
  // 11. AMHARIC - GRADE 11 & 12
  {
    id: 'note-amh-11-u1',
    subjectId: 'amharic',
    subjectName: 'Amharic',
    grade: 'Grade 11',
    chapterNumber: 1,
    unitNumber: 1,
    title: 'የአማርኛ ስነ-ሰዋስው፡ የቃላት ክፍሎችና አፈጣጠር',
    readingTimeMinutes: 10,
    summary: 'የስም፣ ቅጽል፣ ግስ እና መስተፃምር አወቃቀር፣ የቅጥያዎች ሚና እና የቃላት ምስረታ ደንቦች ጥልቅ ትንታኔ።',
    tableOfContents: ['1. የቃላት ክፍሎች ምደባ', '2. ጥገኛና ነፃ ቅጥያዎች', '3. የስም እና የግስ አፈጣጠር', '4. የማጠቃለያ ልምምድ'],
    keyTerms: [
      { term: 'ቅጥያ (Affix)', definition: 'በቃሉ መነሻ፣ መካከለኛ ወይም መጨረሻ ላይ በመጨመር አዲስ ትርጉም ወይም ሰዋስዋዊ ተግባር የሚሰጥ የስነ-ድምፅ አካል።' },
      { term: 'መድረሻ ቅጥያ (Suffix)', definition: 'በቃላት መጨረሻ ላይ የሚጨመር ቅጥያ (ለምሳሌ፡ -ኦች፣ -ነት፣ -ኛ)።' },
      { term: 'ግስ (Verb)', definition: 'ድርጊትን፣ ሁኔታን ወይም ክስተትን በጊዜ አመልካችነት የሚገልጽ የቋንቋ ምሰሶ።' },
    ],
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    resourceUrl: '/resources/amharic-grade11-unit1.pdf',
    resourceName: 'Grade 11 Amharic Unit 1 Notes & Exercises.pdf',
    content: [
      {
        sectionTitle: '1. የቃላት ክፍሎችና ሰዋሰዋዊ ተግባራቸው',
        body: 'በአማርኛ ቋንቋ ቃላት እንደሚያከናውኑት ሰዋሰዋዊ ሚና በዋናነት በስም፣ ተውላጠ-ስም፣ ቅጽል፣ ግስ፣ ተውሳከ-ግስ፣ መስተዋድድ፣ መስተፃምር እና ቃለ-አጋኖ ይከፈላሉ።',
        bulletPoints: [
          'ስም፡ ሰዎችን፣ ቦታዎችን፣ ቁሳቁሶችን ወይም ረቂቅ ሀሳቦችን የሚሰይም።',
          'ቅጽል፡ የስምን ባህሪ፣ መጠን ወይም አይነት የሚያጎላ።',
          'ግስ፡ ድርጊት ወይም ሁኔታን ከጊዜና ባለቤት ጋር የሚያጣቅስ።',
        ],
        calloutBox: {
          title: 'የፈተና ምክር',
          text: 'የብሔራዊ ፈተና ጥያቄዎች ብዙውን ጊዜ በቅጥያዎች ስራና በቃላት አመሰራረት ደንቦች ላይ ያተኩራሉ።',
          type: 'tip',
        },
      },
    ],
  },
  // 12. AFAAN OROMOO - GRADE 11 & 12
  {
    id: 'note-afo-11-u1',
    subjectId: 'afan-oromoo',
    subjectName: 'Afaan Oromoo',
    grade: 'Grade 11',
    chapterNumber: 1,
    unitNumber: 1,
    title: 'Caasluga Afaan Oromoo: Caasaa Jechootaafi Hunda\'ina Himootaa',
    readingTimeMinutes: 11,
    summary: 'Qaamolee dubbii, dhamjecha hirkataafi of-danda\'aa, caasaa himaa (SOV - Matima, Antima, Gochima).',
    tableOfContents: ['1. Qaamolee Dubbii Ijoo', '2. Dhamjechoota Afaan Oromoo', '3. Caasaa Himootaa (SOV)', '4. Shaakala Qormaataa'],
    keyTerms: [
      { term: 'Dhamjecha (Morpheme)', definition: 'Kutaa jechaa isa xiqqaafi hiika qabu ykn tajaajila caaslugaa kennu.' },
      { term: 'Matima (Subject)', definition: 'Qaama himaa isa gocha raawwatu ykn waa\'een isaa himamu.' },
      { term: 'Gochima (Verb)', definition: 'Jecha gocha, ta\'iinsa ykn haala agarsiisu.' },
    ],
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    resourceUrl: '/resources/afaan-oromoo-grade11-unit1.pdf',
    resourceName: 'Grade 11 Afaan Oromoo Unit 1 Study Guide.pdf',
    content: [
      {
        sectionTitle: '1. Caasaa Hima Afaan Oromoo (Subject - Object - Verb)',
        body: 'Afaan Oromoo keessatti tartiibni himaa idilee Matima (Subject), Antima (Object), fi Gochima (Verb) dha. Kunis gabaabinaan SOV jedhama.',
        bulletPoints: [
          'Matimni yeroo baay\'ee jalqaba himaa irratti argama.',
          'Gochimni dhuma himaa irratti argamuun himicha xumura.',
          'Dhamjechi Maxxantuu dhuma jechootaa irratti dabalamuun tajaajila hedduu kenna.',
        ],
        calloutBox: {
          title: 'Gorsa Qormaataa',
          text: 'Tartiiba caasaa himaa eeguufi fayyadama qubee gurguddaafi mallattoolee tuqaa sirriitti beekuun qabxii olaanaa fida.',
          type: 'tip',
        },
      },
    ],
  },
  // 13. HPE (HEALTH & PHYSICAL EDUCATION)
  {
    id: 'note-hpe-11-u1',
    subjectId: 'hpe',
    subjectName: 'HPE',
    grade: 'Grade 11',
    chapterNumber: 1,
    unitNumber: 1,
    title: 'Physical Fitness Components & Energy Systems',
    readingTimeMinutes: 9,
    summary: 'Understand health-related vs skill-related fitness, ATP-PC and aerobic energy pathways, exercise physiology, and athletic training principles.',
    tableOfContents: ['1. Health-Related vs Skill-Related Fitness', '2. Aerobic & Anaerobic Energy Systems', '3. The FITT Principle of Training', '4. Sports Injury Prevention'],
    keyTerms: [
      { term: 'Cardiovascular Endurance', definition: 'The capacity of heart and lungs to supply oxygenated blood during continuous physical activity.' },
      { term: 'FITT Principle', definition: 'Frequency, Intensity, Time, and Type of exercise prescription.' },
      { term: 'Anaerobic Glycolysis', definition: 'Energy production pathway breaking down glucose without oxygen, yielding lactic acid.' },
    ],
    formulas: [
      { name: 'Target Heart Rate (Karvonen formula)', formula: 'THR = ((HR_{max} - HR_{rest}) \\times \\% \\text{Intensity}) + HR_{rest}', explanation: 'Calculates optimal cardiovascular conditioning training zone.' },
    ],
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    resourceUrl: '/resources/hpe-grade11-unit1.pdf',
    resourceName: 'Grade 11 HPE Fitness & Wellness Guide.pdf',
    content: [
      {
        sectionTitle: '1. Health-Related Fitness Components',
        body: 'Physical conditioning is categorized into components directly tied to lifelong wellness and disease prevention: cardiovascular endurance, muscular strength, muscular endurance, flexibility, and body composition.',
        bulletPoints: [
          'Aerobic workouts target the cardiovascular system through sustained activities (running, swimming, cycling).',
          'Muscular strength is assessed via maximal force production in single efforts.',
          'Flexibility maintains range of motion and prevents musculoskeletal injury.',
        ],
        calloutBox: {
          title: 'Exam Note',
          text: 'Remember the five health-related fitness components versus the six skill-related components (agility, balance, coordination, power, reaction time, speed).',
          type: 'info',
        },
      },
    ],
  },
];
